[package]
name = "ethereum-pyspec-db"
version = "0.0.0"
edition = "2021"

[dependencies]
anyhow = "1.0.52"
bytes = "1.1.0"
ethereum-types = "0.12.1"
lmdb = "0.8.0"
lmdb-sys = "0.8.0"
once_cell = "1.9.0"
rlp = "0.5.1"
sha3 = "0.10.0"

[dev-dependencies]
tempfile = "3.2.0"
